"""empty message

Revision ID: e24dbaa03564
Revises: 06aa5fb2e019
Create Date: 2022-04-07 11:15:42.592771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24dbaa03564'
down_revision = '06aa5fb2e019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('det_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'det_qty')
    # ### end Alembic commands ###
